version: '3'
services:
    web:
        build:
            context: .
            dockerfile: DockerFileDev
        ports:
            - "3001:3001"
            - "3000:3000"
        command: npm start
        environment:
            DBHOST: pg
            CHOKIDAR_USEPOLLING: "true"
            # - CHOKIDAR_INTERVAL=1000
        volumes:
            - .:/usr/src/app
            - /usr/src/app/server/node_modules
            - /usr/src/app/client/node_modules
    pg:
        image: postgres:latest
        container_name: postgresdb
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: thesisEats
            POSTGRES_DB: planeats

